# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "~/My/ubuntu-desktop-share", "/ubuntu-desktop-share"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = "6144"
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--audioout", "on"]
    v.customize ["modifyvm", :id, "--audiocontroller", "hda"]
    v.customize ["modifyvm", :id, "--usb", "on"]
    v.customize ["modifyvm", :id, "--usbxhci", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
    sudo apt-get install -y firefox ristretto vlc mousepad
    sudo add-apt-repository ppa:unit193/encryption
    sudo apt-get update
    sudo apt-get install -y veracrypt
    sudo setxkbmap de
  SHELL

end
