# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"

  config.ssh.insert_key = false
  config.vm.synced_folder "~/My/Workspaces", "/opt/workspaces"

  # install private key
  config.vm.provision "file", source: "~/.ssh/id_rsa_do2", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: <<-SHELL
    chmod 600 /home/vagrant/.ssh/id_rsa
    sudo mkdir /root/.ssh
    sudo cp /home/vagrant/.ssh/id_rsa /root/.ssh/id_rsa
    sudo chmod 600 /root/.ssh/id_rsa
  SHELL

  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = true
  end

end
